# Generated by Django 4.0.1 on 2023-07-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number_of_pages',
            field=models.IntegerField(null=True),
        ),
    ]
